import { NgModuleComponent } from "@angular/core"
import { BrowserModuleComponent } from "@angular/platform-browser"

import { AppRoutingModuleComponent } from "./app-routing.module"
import { AppComponent } from "./app.component"
import { HeaderComponent } from "./header/header.component"
import { FooterComponent } from "./footer/footer.component"
import { HomeComponent } from "./home/home.component"
import { LayoutsComponent } from "./layouts/layouts.component"
import { ThemesComponent } from "./themes/themes.component"
import { ModulesComponent } from "./modules/modules.component"
import { BaseComponent } from "./base/base.component"
import { StatesComponent } from "./states/states.component"
import { IconsComponent } from "./base/icons/icons.component"
import { TypographyComponent } from './base/typography/typography.component'
import { AccessibilityComponent } from "./base/accessibility/accessibility.component"
import { ColorPaletteComponent } from "./base/color-palette/color-palette.component"
import { DocumentComponent } from "./base/document/document.component"
//import { FooterComponent } from "./base/footer/footer.component"
import { NavigationComponent } from "./base/navigation/navigation.component"
//import { FormsComponent } from "./base/forms/forms.component"
//import { IconsComponent } from "./base/icons/icons.component"
import { LogosComponent } from "./base/logos/logos.component"
import { SizeConversionsComponent } from "./base/size-conversions/size-conversions.component"
import { LayoutsHomeComponent } from "./layouts/layouts-home/layouts-home.component"
import { FullPageComponent } from "./layouts/fullpage/fullpage.component"
import { NestedFiveColComponent } from "./layouts/nested-five-col/nested-five-col.component"
import { NestedFourColComponent } from "./layouts/nested-four-col/nested-four-col.component"
import { NestedRowsComponent } from "./layouts/nested-rows/nested-rows.component"
import { NestedSixColComponent } from "./layouts/nested-six-col/nested-six-col.component"
import { NestedThreeColComponent } from "./layouts/nested-three-col/nested-three-col.component"
import { NestedTwoColComponent } from "./layouts/nested-two-col/nested-two-col.component"
import { RowsComponent } from "./layouts/rows/rows.component"
import { ModulesHomeComponent } from "./modules/modules-home/modules-home.component"
import { AccordionsComponent } from "./modules/accordions/accordions.component"
import { BlockquoteComponent } from "./modules/blockquote/blockquote.component"
import { CodeComponent } from "./modules/code/code.component"
import { ContactComponent } from "./modules/contact/contact.component"
import { CorrectionUpdateComponent } from "./modules/correction-update/correction-update.component"
import { EnergyEducationComponent } from "./modules/energy-education/energy-education.component"
import { FancyboxComponent } from "./modules/fancyapps/fancyapps.component"
import { ModalsComponent } from "./modules/modals/modals.component"
import { EnlargeContentComponent } from "./modules/enlarge-content/enlarge-content.component"
import { iFrameComponent } from "./modules/iframe/iframe.component"
import { ImagesComponent } from "./modules/images/images.component"
import { NenuComponent } from "./modules/menu/menu.component"
import { CarouselsComponent } from "./modules/carousels/carousels.component"
import { HomepageComponent } from "./modules/homepage/homepage.component"
import { MultiComponent } from "./modules/multi/multi.component"
import { OutlooksComponent } from "./modules/outlooks/outlooks.component"
import { FootnotesComponent } from "./modules/footnotes/footnotes.component"
import { FormsComponent } from "./modules/forms/forms.component"
import { MessagingComponent } from "./modules/messaging/messaging.component"
import { MessagingWideComponent } from "./modules/messaging-wide/messaging-wide.component"
import { PageTitlesComponent } from "./modules/page-titles/page-titles.component"
import { UnorderedListsComponent } from "./modules/unordered-lists/unordered-lists.component"
import { ReportHeadersComponent } from "./modules/report-headers/report-headers.component"
import { RevisionNoticeComponent } from "./modules/revision-notice/revision-notice.component"
import { TablesComponent } from "./modules/tables/tables.component"
import { TabsComponent } from "./modules/tabs/tabs.component"
import { VisualizationsComponent } from "./modules/visualizations/visualizations.component"
import { StatesHomeComponent } from "./states/states-home/states-home.component"
import { BuildAnchorComponent } from "./states/build-anchor/build-anchor.component"
import { CalculatedNumberedListsComponent } from "./states/calculated-numbered-lists/calculated-numbered-lists.component"
import { EmptyListItemsComponent } from "./states/empty-list-items/empty-list-items.component"
import { HeaderShrinkExpandComponent } from "./states/header-shrink-expand/header-shrink-expand.component"
import { StickyTableHeadersComponent } from "./states/sticky-table-headers/sticky-table-headers.component"
import { ToggleLayersComponent } from "./states/toggle-layers/toggle-layers.component"
import { VideosComponent } from "./states/videos/videos.component"
import { ThemesHomeComponent } from "./themes/themes-home/themes-home.component"
import { FAQOneComponent } from "./themes/faq-one/faq-one.component"
import { FAQTwoComponent } from "./themes/faq-two/faq-two.component"
import { StarterTemplateComponent } from "./themes/starter-template/starter-template.component"
import { BaseHomeComponent } from "./base . base-home . base-home.component";






@NgModule({
  declarations: [AppComponent, HeaderComponent, FooterComponent, HomeComponent, LayoutsComponent, ThemesComponent, ModulesComponent, BaseComponent, StatesComponent, IconsComponent, TypographyComponent],
  imports: [BrowserModule, AppRoutingModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
